### ISSUE TITLE
Gramtical error

### ISSUE THREAD

**Issue by vinutnaruni** [officeneerajsaini/portfolio#1]
What technologies i Know ?
is gramatically incorrect and I should be capital too

Correct sentences would be

What technologies do I know?
List the technologies I have expertise in.

<img width="1610" alt="Screenshot 2024-01-27 at 9 27 29 PM" src="https://github.com/officeneerajsaini/portfolio/assets/142968419/78263d01-d988-4671-bd22-50b63c2cb7d6">

**Comment by officeneerajsaini** [comment]
Yeah thank you @vinutnaruni .
